spring:
  application:
    name: zuul
  redis:
    # 其中spring.redis.database的配置通常使用0即可，
    # Redis在配置的时候可以设置数据库数量，默认为16，可以理解为数据库的schema
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 2000
server:
  port: 80

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 10000
    # 最大连接数
    max-total-connections: 200
    # 每个路由最大连接数
    max-per-route-connections: 100

  routes:
    user:
      path: /user/**
      url: http://localhost:8001/user/
      serviceId: user
      # stripPrefix 默认为true（关闭所有设置的path前缀即转发时去除前缀），设置为false保留前缀
      stripPrefix: true
      # sensitiveHeaders为空为不做任何请求头部header拦截
      sensitiveHeaders:
      # 路由的最大请求信号量，高于则拒绝
      semaphore:
        maxSemaphores: 100
